import test from 'node:test';import assert from 'node:assert/strict';
let counter=0,settings=new Map(),rollValue=1,failDebit=false,failAward=false;const namespace='telynors-events-page';
class App {constructor(options){this.options=options;}render(){this.rendered=true;return this;}}
globalThis.foundry={applications:{api:{ApplicationV2:App}},utils:{randomID:()=>String(++counter)}};
globalThis.Hooks={on:()=>{}};globalThis.document={createElement:()=>({}),head:{append:()=>{}}};
const gm={id:'gm',name:'GM',isGM:true},a={id:'a',name:'A',isGM:false},b={id:'b',name:'B',isGM:false};const users=[gm,a,b];users.get=id=>users.find(u=>u.id===id);
const currency={id:'coin',uuid:'Actor.actor-a.Item.coin',name:'Tickets',type:'loot',system:{quantity:20},flags:{},getFlag(s,k){return this.flags[s]?.[k]},async update(data){this.system.quantity=data['system.quantity'];this.flags[namespace]??={};this.flags[namespace].boardPayments=data[`flags.${namespace}.boardPayments`];if(failDebit){failDebit=false;throw Error('Disconnected after debit');}}};
function actor(id,items){items.get=key=>items.find(i=>i.id===key);return {id,img:'',items,testUserPermission:()=>true,async createEmbeddedDocuments(_kind,sources){for(const source of sources)this.items.push({id:'reward'+(++counter),system:source.system,flags:source.flags,getFlag(s,k){return this.flags[s]?.[k]}});if(failAward){failAward=false;throw Error('Disconnected after award');}}};}
const aa=actor('actor-a',[currency]),bb=actor('actor-b',[]);const actors=[aa,bb];actors.get=id=>actors.find(x=>x.id===id);a.character=aa;b.character=bb;
globalThis.game={user:gm,users,actors,settings:{settings:new Map(),register(id,key,config){this.settings.set(id+'.'+key,config);if(!settings.has(key))settings.set(key,structuredClone(config.default));},get(id,key){return key==='database'?{recipients:{}}:settings.get(key)},async set(id,key,value){settings.set(key,structuredClone(value));}}};
globalThis.Roll=class{async evaluate(){return {total:rollValue}}};globalThis.fromUuid=async()=>({documentName:'Item',system:{quantity:1},toObject:()=>({name:'Reward',system:{quantity:1}})});
let plugin;globalThis.TelyEvents={register:(_id,def)=>plugin=def};
const core=await import('../events/multiplayer-board-game.js');
const event={id:'test'};const call=(user,action,data={})=>core.actionHandler({event,user,action,data,context:{requestId:'tx'+(++counter)}});
async function reset(){settings.set('boardGames',{});currency.system.quantity=20;currency.flags={};aa.items.splice(1);rollValue=1;const c=core.defaults();c.tiles=Array.from({length:4},(_,i)=>({id:'tile'+i,label:'Tile'+i,effect:'none',color:'#315168',image:''}));c.currency={uuid:'Item.currency',name:'Tickets',type:'loot'};c.cost=2;c.rewards=[{id:'r1',uuid:'Item.reward',name:'Prize',img:'',tier:1,amount:3,stock:1},{id:'r2',uuid:'Item.reward2',name:'Other',img:'',tier:2,amount:1,stock:2}];await call(gm,'configure',{config:c});await call(a,'join');await call(b,'join');await call(gm,'start');return c;}
test('all nine requested effects exist',()=>assert.deepEqual(core.FX.map(x=>x[1]),['No effect','Move 1 space forward','Tier 1 Reward','Tier 2 Reward','Tier 3 Reward','Lose 1 turn','Return to Start','Choose Reward Tier','Reward of Choice']));
test('turn and tile ownership reject arbitrary actions',async()=>{await reset();await assert.rejects(()=>call(b,'roll'),/not your turn/);await assert.rejects(()=>call(a,'tile',{index:0}),/Roll before/);await call(a,'roll');await assert.rejects(()=>call(a,'roll'),/Resolve/);await assert.rejects(()=>call(a,'tile',{index:0}),/occupied/);assert.equal(currency.system.quantity,18);});
test('paid roll debit recovery never charges twice',async()=>{await reset();failDebit=true;await assert.rejects(()=>call(a,'roll'),/Disconnected/);assert.equal(currency.system.quantity,18);assert.ok(core.getBoard('test').pending);await call(a,'recover');assert.equal(currency.system.quantity,18);assert.equal(core.getBoard('test').players.a.position,1);});
test('stock reservation, award recovery and 100 points are idempotent',async()=>{const c=await reset();c.tiles[1].effect='tier1';await call(gm,'configure',{config:c});await call(a,'roll');failAward=true;await assert.rejects(()=>call(a,'tile',{index:1}),/Disconnected/);let board=core.getBoard('test');assert.equal(core.stock(board,c.rewards[0]),0);assert.equal(board.players.a.points,0);assert.equal(aa.items.length,2);assert.equal(aa.items[1].system.quantity,3);await call(a,'recover');board=core.getBoard('test');assert.equal(aa.items.length,2);assert.equal(board.players.a.points,100);assert.equal(core.getBoard('test').players.b.points,0);await assert.rejects(()=>call(a,'tile',{index:1}),/not your turn/);});
test('stock is shared, sold-out rewards end a turn without points',async()=>{const c=await reset();c.tiles[1].effect='tier1';await call(gm,'configure',{config:c});await call(a,'roll');await call(a,'tile',{index:1});await call(gm,'pass');await call(a,'roll');let board=core.getBoard('test');board.players.a.position=1;await game.settings.set(namespace,'boardGames',{test:board});await call(a,'tile',{index:1});assert.equal(core.getBoard('test').players.a.points,100);assert.equal(aa.items.length,2);});
test('move, return to Start and lose one turn',async()=>{const c=await reset();c.tiles[1].effect='forward';c.tiles[2].effect='skip';await call(gm,'configure',{config:c});await call(a,'roll');await call(a,'tile',{index:1});assert.equal(core.getBoard('test').players.a.position,2);await call(a,'tile',{index:2});assert.equal(core.getBoard('test').players.a.skip,1);await call(gm,'pass');assert.equal(core.getBoard('test').players.a.skip,0);assert.equal(core.getBoard('test').order[core.getBoard('test').turn],'b');await call(gm,'pass');c.tiles[3].effect='start';await call(gm,'configure',{config:c});await call(a,'roll');await call(a,'tile',{index:3});assert.equal(core.getBoard('test').players.a.position,0);});
test('choice tiles enforce selected tier and existing reward',async()=>{const c=await reset();c.tiles[1].effect='chooseTier';await call(gm,'configure',{config:c});await call(a,'roll');await assert.rejects(()=>call(a,'tile',{index:1,tier:3}),/still has/);await call(a,'tile',{index:1,tier:2});assert.equal(core.getBoard('test').players.a.points,100);await call(gm,'pass');c.tiles[2].effect='choice';await call(gm,'configure',{config:c});await call(a,'roll');await assert.rejects(()=>call(a,'tile',{index:2,rewardId:'fake'}),/available/);await call(a,'tile',{index:2,rewardId:'r1'});assert.equal(core.getBoard('test').players.a.points,200);});
test('currency insufficiency and player configuration rejected',async()=>{await reset();currency.system.quantity=1;await assert.rejects(()=>call(a,'roll'),/need 2/);assert.equal(core.getBoard('test').phase,'roll');await assert.rejects(()=>call(a,'configure',{config:core.defaults()}),/GM only/);});
test('movement-only loop terminates',async()=>{const c=await reset();c.tiles.forEach(t=>t.effect='forward');await call(gm,'configure',{config:c});await call(a,'roll');for(let n=0;n<4;n++)await call(a,'tile',{index:core.getBoard('test').players.a.position});assert.equal(core.getBoard('test').phase,'roll');assert.equal(core.getBoard('test').order[core.getBoard('test').turn],'b');});

test('popup and designer templates render the mapped board and all effects',async()=>{await reset();const popup=new core.BoardPopup('test'),designer=new core.BoardDesigner('test');const html=await popup._renderHTML(),editor=await designer._renderHTML();assert.equal((html.match(/data-board="tile"/g)||[]).length,4);assert.match(html,/A.*points/s);for(const [,label]of core.FX)assert.ok(editor.includes(label));assert.match(editor,/Stock/);assert.match(editor,/DM Board Game Designer/);});
